print("Hola bienvenidos al generador de nombres by Luis, este generador te puede funcionar ya sea para crear el nombre de una banda o crear el nombre de un emprendimiento\n\nVamos a Comenzar!!")
ciudad = input("Cuál es el nombre de la ciudad donde naciste?\n")
nombre_mascota = input("Cual es el nombre de tu mascota?\n")
nombre_generado = ("El Nuevo nombre generado es: \n" + nombre_mascota + " de " + ciudad)
print(nombre_generado)
