print("Bienvenidos al calculador de propinas by Luis")
total_bill = input("Cuanto es el total de la factura? $")
tip = input("Cual es el porcentaje de propina que le gustaria dar? 10, 12 o 15? : ")
persons = input("En cuantas personas se divide la factura? : ")
tip_porc = (float(tip) / 100 + 1)
bill_and_tip = (float(total_bill) * tip_porc)
bill_by_pers = round((bill_and_tip / (float(persons))), 2)
message = (f"Cada persona debe pagar: ${bill_by_pers:.2f}, incluyendo la propina.")
print(message)
print("Muchas gracias, vuelva pronto.")
